# Generated by Django 3.2.16 on 2025-02-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogicumUser',
        ),
    ]
